server:
  additionalApplications:
    - name: fall-project
      namespace: default
      project: default
      source:
        repoURL: '${ fall-project_repo }'
        path: helm/fall-project
        targetRevision: main
        helm:
          valueFiles:
            - values.aws.yaml
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
