configs:
    credentialTemplates:
        fall-project:
            url: '${ fall-project_repo }'
            sshPrivateKey: '${ fall-project_repo_secret_key }'
            type: git

    repositories:
        fall-project:
            name: fall-project
            url: '${ fall-project_repo }'
            type: git

